#
# Your Crowdin credentials
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "./src"
# base_url: "./src/"

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files:
  [
    {
      source: "/pages/en/**/*.mdx",
      translation: "/pages/%two_letters_code%/**/%file_name%.mdx",
      ignore: [
          "/pages/en/blog-index.mdx",
          "/pages/en/pgp.mdx", 
          "/pages/en/xmr2.mdx",
          "/pages/en/snowflake.mdx"
      ],
    },
    {
      source: "/pages/404.mdx",
      translation: "/pages/404_%two_letters_code%.mdx",
    },
    {
      source: "/assets/data/pages/en/**/*.json",
      translation: "/assets/data/pages/%two_letters_code%/**/%file_name%.json",
    },
    {
      source: "/assets/data/layout/en/**/*.json",
      translation: "/assets/data/layout/%two_letters_code%/**/%file_name%.json",
    },
  ]
